-- 用户表
CREATE TABLE `SIP_USER`
(`ID` VARCHAR(32) NOT NULL,
`USERNAME` VARCHAR(100) NOT NULL COMMENT '账号',
`PASSWORD` VARCHAR(32) NOT NULL COMMENT '密码',
`USER_INFO_ID` VARCHAR(32) COMMENT '拓展表外键',
`STATUS` INT DEFAULT '0' COMMENT '状态(-1:禁用;0:锁定;1:活动)',
`MAIN_STATION_ID` VARCHAR(32) COMMENT '主岗id',
`VISIT` VARCHAR(10) COMMENT '是否具有外网访问权限(0:有权限,1:无权限)',
`CREATE_TIME` DATETIME COMMENT '创建时间',
`CREATE_USER` VARCHAR(50) COMMENT '创建人',
`MODIFY_TIME` DATETIME COMMENT '修改时间',
`MODIFY_USER` VARCHAR(50) COMMENT '修改操作人',
PRIMARY KEY (`ID`));

-- 用户拓展表
CREATE TABLE `SIP_USER_INFO`
(`ID` VARCHAR(32) NOT NULL,
`USER_CHINESE_NAME` VARCHAR(100) COMMENT '中文名称',
`JOB_NUMBER` VARCHAR(100) COMMENT '工号',
`SEX` VARCHAR(10) COMMENT '性别(1男,2女)',
`EMAIL` VARCHAR(100) COMMENT '邮箱',
`BIRTHDAY` DATETIME COMMENT '生日',
`MOBILE` VARCHAR(11) COMMENT '移动电话',
`TELEPHONE` VARCHAR(20) COMMENT '固定电话号',
`USER_THEME` VARCHAR(10) COMMENT '知识库主题',
`IP` VARCHAR(20) COMMENT '用户ip',
`DESC_CONTENT` VARCHAR(600) COMMENT '备注',
`AVATAR` VARCHAR(400) COMMENT '头像',
`START_DATE` DATETIME COMMENT '开始时间',
`END_DATE` DATETIME COMMENT '结束时间',
`CREATE_TIME` DATETIME COMMENT '创建时间',
`CREATE_USER` VARCHAR(50) COMMENT '创建人',
`MODIFY_TIME` DATETIME COMMENT '修改时间',
`MODIFY_USER` VARCHAR(50) COMMENT '修改操作人',
PRIMARY KEY (`ID`));

